# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
version: '2'

run:
  build-tags:
    - codeanalysis
  tests: false

linters:
  disable:
    - staticcheck
  enable:
    - copyloopvar
    - dogsled
    - errcheck
    - gosec
    - misspell
    - nakedret
    - revive
    - unconvert

issues:
  exclude-generated: lax
  exclude:
    - "Error return value of `.*Close` is not checked"
    - "Error return value of `.*Flush` is not checked"
    - "G304: Potential file inclusion via variable"
    - "exported: exported .* should have comment or be unexported"
    - "package-comments: should have a package comment"
    - "comment on exported const .* should be of the form"
  exclude-dirs:
    - third_party$
    - builtin$
    - examples$
