# yamllint disable-file
# SPDX-FileCopyrightText: (C) 2024 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "config-provisioner.fullname" . }}
  labels:
    {{- include "config-provisioner.labels" . | nindent 4 }}
data:
  logging.yaml: |-
{{ toYaml .Values.logging | indent 4 }}

