# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: provisioner-nexus-tenancy-role
  namespace: {{ .Values.configProvisioner.namespace }}
rules:
  - apiGroups: ["network.edge-orchestrator.intel.com"]
    resources: ["networks"]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: ["apimappingconfig.edge-orchestrator.intel.com"]
    resources: ["apimappingconfigs"]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups: ["orgactivewatcher.edge-orchestrator.intel.com"]
    resources: ["orgactivewatchers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["projectactivewatcher.edge-orchestrator.intel.com"]
    resources: ["projectactivewatchers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["orgwatcher.edge-orchestrator.intel.com"]
    resources: ["orgwatchers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["projectwatcher.edge-orchestrator.intel.com"]
    resources: ["projectwatchers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["tenancy.edge-orchestrator.intel.com"]
    resources: ["multitenancies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["runtime.edge-orchestrator.intel.com"]
    resources: ["runtimes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["runtimeorg.edge-orchestrator.intel.com"]
    resources: ["runtimeorgs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["runtimefolder.edge-orchestrator.intel.com"]
    resources: ["runtimefolders"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["runtimeproject.edge-orchestrator.intel.com"]
    resources: ["runtimeprojects"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [ "license.edge-orchestrator.intel.com" ]
    resources: [ "licenses" ]
    verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: provisioner-nexus-permission
  namespace: {{ .Values.configProvisioner.namespace }}
rules:
  - apiGroups: ["tenancy.edge-orchestrator.intel.com"]
    resources: ["multitenancies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["config.edge-orchestrator.intel.com"]
    resources: ["configs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["runtime.edge-orchestrator.intel.com"]
    resources: ["runtimes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["orgwatcher.edge-orchestrator.intel.com"]
    resources: ["orgwatchers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["projectwatcher.edge-orchestrator.intel.com"]
    resources: ["projectwatchers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["orgactivewatcher.edge-orchestrator.intel.com"]
    resources: ["orgactivewatchers"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: ["projectactivewatcher.edge-orchestrator.intel.com"]
    resources: ["projectactivewatchers"]
    verbs: ["get", "list", "watch", "delete", "patch"]
  - apiGroups: ["org.edge-orchestrator.intel.com"]
    resources: ["orgs"]
    verbs: ["get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["org.edge-orchestrator.intel.com"]
    resources: ["orgs/status"]
    verbs: ["get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["folder.edge-orchestrator.intel.com"]
    resources: ["folders"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["project.edge-orchestrator.intel.com"]
    resources: ["projects"]
    verbs: ["get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["project.edge-orchestrator.intel.com"]
    resources: ["projects/status"]
    verbs: ["get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["runtimefolder.edge-orchestrator.intel.com"]
    resources: ["runtimefolders"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["runtimeorg.edge-orchestrator.intel.com"]
    resources: ["runtimeorgs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["runtimeproject.edge-orchestrator.intel.com"]
    resources: ["runtimeprojects"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [ "license.edge-orchestrator.intel.com" ]
    resources: [ "licenses" ]
    verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provisioner-nexus-permission
  namespace: {{ .Values.configProvisioner.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.configProvisioner.serviceAccount }}
    namespace: {{ .Values.configProvisioner.namespace }}
roleRef:
  kind: ClusterRole
  name: provisioner-nexus-permission
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provisioner-nexus-tenancy-role
  namespace: {{ .Values.configProvisioner.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.configProvisioner.serviceAccount }}
    namespace: {{ .Values.configProvisioner.namespace }}
roleRef:
  kind: ClusterRole
  name: provisioner-nexus-tenancy-role
  apiGroup: rbac.authorization.k8s.io
