# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
description: Tenant Controller
name: app-orch-tenant-controller
version: 0.6.1
annotations:
  revision: ""
  created: ""
appVersion: "0.6.1"
