---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Post-Merge CI Pipeline

on:
  push:
    branches:
      - main
      - release-*
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  attestations: read
  checks: read
  deployments: read
  discussions: read
  issues: read
  models: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  statuses: read
  security-events: write
  id-token: write

jobs:
  post-merge-pipeline:
    uses: open-edge-platform/orch-ci/.github/workflows/post-merge.yml@4c94cdd01e58beab5f822f1eeb0439a523018a55 # v0.1.5
    with:
      run_version_check: true
      run_dep_version_check: true
      run_build: true
      run_docker_build: true
      run_docker_push: true
      run_helm_build: true
      run_helm_push: true
      run_version_tag: true
      run_artifact: false
      project_folder: ""
    secrets: inherit