---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Post-Merge CI Pipeline

on:
  push:
    branches:
      - main
      - release-*
  workflow_dispatch:

permissions: {}

jobs:
  post-merge-pipeline:
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: open-edge-platform/orch-ci/.github/workflows/post-merge.yml@aed8b53da7ba686d91c1d16fc099f28a37b2d6de # v0.1.19
    with:
      run_version_check: true
      run_dep_version_check: true
      run_build: true
      run_docker_build: true
      run_docker_push: true
      run_helm_build: true
      run_helm_push: true
      run_version_tag: true
      run_artifact: false
      project_folder: ""
    secrets:
      inherit # zizmor: ignore[secrets-inherit]